### ISSUE TITLE
Questions about pain SPC chart 2a and 2b - interval charts

### ISSUE THREAD

**Issue by SJaffa** [inform-us/metrics-rules#5]
### Chart 2a and 2b
https://github.com/inform-us/metrics-rules/blob/fdea8cb99d47fc8c61bacd744fa7fe5e04800541/rules/pain.md?plain=1#L120-L136

- Is this looking at the **hourly epoch scores** (after filtering out multiple scores in an hour or multiple types of scores at the same time) or **all scores** that are entered in the flowsheet?
- Is GREEN going to look at intervals less than **4 hours** even though we use **5 hours** in the rest of the code?
- Is RED going to look at intervals less than **1 hour** even though we use **75 minutes** in the rest of the code?

https://github.com/inform-us/metrics-rules/blob/fdea8cb99d47fc8c61bacd744fa7fe5e04800541/rules/pain.md?plain=1#L138-L140

These points need to be resolved before we can write the code.

**Comment by VoegeleP** [comment]
Is this looking at the hourly epoch scores (after filtering out multiple scores in an hour or multiple types of scores at the same time) or all scores that are entered in the flowsheet? **After filtering.** 
Is GREEN going to look at intervals less than 4 hours even though we use 5 hours in the rest of the code? **Yes due to the fact that we don't want to give leeway for recurrent missing scores.** 
Is RED going to look at intervals less than 1 hour even though we use 75 minutes in the rest of the code? **Yes due to the fact that we don't want to give leeway for recurrent missing scores.**
